// Generated by CoffeeScript 1.9.1
yOSON.AppSchema.modules = {
  "fileuploader": {
    "controllers": {
      "home": {
        "actions": {
          "index": function() {
            yOSON.AppCore.runModule("fileuploader");
            yOSON.AppCore.runModule("preview_fileuploader");
            yOSON.AppCore.runModule("manager_fileuploader");
          },
          "by_default": function() {}
        },
        "all_actions": function() {}
      },
      "by_default": function() {}
    },
    "all_controllers": function() {}
  },
  "by_default": function() {},
  "all_modules": function() {}
};
